config/routes.rb
Rails.application.routes.draw do

# userと同様にskip: :[password, :registratin]を記述していたのだがするとNo method error Admin#sessionというエラーがでてしまい調べたところ
# skip の記述を消せば解決するとあったのでその通りにするとエラー解決

  devise_for :admin, controllers: {
    sessions: "admins/sessions"
  }
  devise_for :user, skip: [:password], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
   post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# ファイル構成は指定し、urlは変えたくないのでmoduleを使用
 scope module: :users do
  # 通常の指定方法
  # メソッド(get) "url", to: "controller#action", as: "パス名指定"
   get "/", to: "homes#top", as: "root"
   get "/about", to: "homes#about"
   # post "/guest_sign_in", to: "homes#guest_sign_in"
  # resourcesメソッド [index,create,new,show,update,edit,destroy]を自動で作成
  # onlyを使うことで不要なルーティングを制限
   resources :users, only:[:show, :edit, :update, :index, :destroy] do
    # member　で自分でアクションを作ることが出来る。　collectionとの違いはurlにidを指定するかしないか
     member do
       get :confirm
       get :like
       get :following
       get :follower

     end
     collection do
      get :search
     end
    # usersにネストさせることでuser_id/postsというように特定のuserのindexとshowにすることができる
     # resources :posts, only: [:index, :show]
   end
   resources :posts, only:[:new, :create, :destroy, :show, :index] do
    member do
     get :confirm
     get :index_user
     get :show_image
    end
    collection do
     get :search
    end
    resources :comments, only:[:index, :create, :destroy]
    # resource,resourcesのどちらでも実装できた。
    # favoritesのshowページが不要で、idの受け渡しも必要ないので、resourceとなっています。
    # とdmmには書いてあった。
    resource :likes, only:[:create, :destroy]
   end
   resources :relationships, only:[:create, :destroy]
 end

 namespace :admins do
  get "/", to: "homes#top"

  resources :users, only: %i[index show edit update] do
   member do
    get :following
    get :follower
   end

   collection do
    get :search
   end
  end
  resources :posts, only: %i[index show destroy] do
   collection do
    get :search
   end
  end
 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  
  attachment :profile_image


  def following?(other_user)
    self.followings.include?(other_user)
  end

  def follow(other_user)
    unless self == other_user
      self.active_relationships.find_or_create_by(followed_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.active_relationships.find_by(followed_id: other_user.id)
    relationship.destroy if relationship
  end

  # 検索で使うsearchメソッドを定義
  def self.search(keyword)
    where(["name like?", "%#{keyword}%"])
  end

# ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  # def active_for_authentication?
  #   super && self.is_active?
  # end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all.page(params[:page]).per(3)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admins_user_path(@user)
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def follower
    @user = User.find(params[:id])
    @users = @user.followers
  end

  
  def search
    @users = User.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end
  
  private
  def user_params
    params.require(:user).permit(:is_active)
  end
  
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
before_action :authenticate_user!

  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.where(post_id: @post.id)
  end

  def create
    # post#showページのコメント投稿formのなかみのアクションです
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id= post.id
    comment.save
    redirect_to post_comments_path(post)
  end

  def destroy
    # find_byメソッドをつかっていたがこちらでもできた。いまいち理解できていない。
    post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(post.id)
  end



  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
    @user = User.find(current_user.id)
    @followings = @user.followings
    @posts = Post.where(user_id: @followings).order(created_at: :DESC).page(params[:page]).per(4)
    @posts_all = Post.all.order(created_at: :DESC).page(params[:page]).per(4)
  end

  def about
  end

end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  def create
    like = Like.new(user_id: current_user.id, post_id: params[:post_id])
    like.save
    redirect_to post_path(params[:post_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    # dataを新規登録するためのインスタンス作成
    post = Post.new(post_params)
    #投稿のuser_idはログイン中のユーザーidに指定
    post.user_id = current_user.id
    # dataをdataベースに保存するためのsaveメソッドを実行
    post.save
    flash[:notice] = "投稿に成功しました!!"
    redirect_to index_user_post_path(post.user_id)
  end

  def index
    # ページネーションを使う
    @posts = Post.all.page(params[:page]).per(3)
  end

# 最初はindexアクションを定義していたがユーザーごとの投稿一覧ページを実装する必要があったので新しいアクションindex_userを追加して
# urlにuser_idを含むposts/user_id/index_userというルーティングを作った。
  def index_user
    @user = User.find(params[:id])
     # 特定のユーザーの投稿一覧だけを取得したいのでwhereメソッドを使う
    # モデル.where(条件)
    @posts = Post.where(user_id:params[:id]).order(created_at: :desc).page(params[:page]).per(2)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  # 画像の詳細（拡大）表示
  def show_image
    @post = Post.find(params[:id])
  end

  def confirm
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to index_user_post_path(@post.user)
  end



  # def search
  #   @posts = Post.search(params[:keyword]).page(params[:page]).per(5)
  #   @keyword = params[:keyword]
  #   render "index"

  # end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image, :genre)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

# userの新規登録でUnpermitted parameters: :authenticity_token, :user, :commitのエラーがでて新規登録できなかったので
# 以下でストロングパラメータを記述をしたら解決した。deviseでは初期設定ででemailとpasswordしか許可されていないのでnameを追加
# before_action :configure_permitted_parameters, if: :devise_controller?

#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
#   end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = "ユーザーをフォローしました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォローに失敗しました"
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = "ユーザーのフォローを解除しました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォロー解除に失敗しました"
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:relationship][:followed_id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, flash: {guest_success: "ゲストユーザーとしてログインしました"}
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected
  # 退会しているか判断するメソッド
   def user_state
    # 入力されたemailからアカウントを一件取得
     @user = User.find_by(email: params[:user][:email])
    # アカウントを取得できなかった場合このメソッドを終了する
     return if !@user
    # 取得したアカウントのパスワードと入力したパスワードが一致しているかを確かめる
     if @user.valid_password?(params[:user][:password])
     end
   end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[following, follower]
  before_action :set_user, except: [:index, :search]

  def index
    @users = User.all
  end

  def show
    @relationship = current_user.active_relationships.find_by(followed_id: @user.id)

    @set_relationship = current_user.active_relationships.new
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(current_user)

  end

  def confirm
  end

  def destroy
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to about_path
  end
 

  def like
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end

  def following
    @users = @user.followings
  end

  def follower
    @users = @user.followers
  end

  # def search
  #   @users = User.search(params[:keyword])
  #   @keyword = params[:keyword]
  #   render "index"
  # end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :profile, :profile_image, :is_active)
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/likes_helper.rb
module Users::LikesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/views/users/users/_list.html.erb
<!--ユーザー情報表示の部分テンプレート-->
<!--users/posts/index_user-->
<!--users/users/like-->
<!---->
<div class="col-3 mt-3 d-flex flex-column ">
  <!--プロフィール画像-->
  <%= link_to user_path(user) do %>
  <div class="d-flex justify-content-center">
    <%= attachment_image_tag user, :profile_image, :fill, 150, 150, fallback:"images/no_image.jpg", class:"rounded-circle";                      %>
  </div>
  <!--ユーザーネーム-->
  <div class="d-flex justify-content-center">
    <h4><%= user.name %></h4>
  </div>
  <% end %>
  <!--follow,follower表示-->
  <div class="d-flex">
    <span class="flex-fill"><p class="d-flex justify-content-center">フォロー<%= user.followings.count %></p></span>
    <span class="flex-fill"><p class="d-flex justify-content-center">フォロワー<%= user.followers.count %></p</span>
  </div>
  
  
  <!--ログインユーザーのときだけ編集アイコン表示-->
  <% if current_user == user %>
  <div class="row d-flex justify-content-center">
    <a class="btn btn-outline-secondary col-5" href="/users/<%= current_user.id %>/edit">
      <i class="fas fa-user-cog"></i>
    </a>
  </div>
  <% end %>
</div>

app/views/users/users/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <h3>本当に退会しますか？</h3>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-3 d-flex justify-content-center">
      <%= link_to user_path(current_user), method: :delete do %>
      <h4>はい</h4>
      <% end %>
    </div>
    <div class="col-3 d-flex justify-content-center">
      <%= link_to user_path(current_user) do %>
      <h4>いいえ</h4>
      <% end %>
    </div>
  </div>

app/views/users/users/edit.html.erb
<div class="container">
  <div class="row">
    <h2>プロフィール編集ページ</h2>
  </div>

  <div class="row justify-content-center">
    <p>
    <%= attachment_image_tag @user, :profile_image, :fill, 1000, 1000, fallback:"images/no_image.jpg",size:'200x200', class:"rounded-circle"; %>
    </p>
  </div>


  <div class="row justify-content-center">
    <%= form_with model:@user, url:user_path(@user.id), local: true do |f| %>
    <div class="form-group">
      <%= f.label :email, class:"form-label" %>
      <%= f.email_field :email, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name, class:"form-label" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :profile, class:"form-label" %>
      <%= f.text_area :profile, class:"form-control" %>
    </div>
    <div class="form-group">
       <%= f.label :プロフィール画像, class: "form_label" %>
       <%= attachment_image_tag @user, :profile_image, :fill, 1000, 1000%>
       <%= f.attachment_field :profile_image %>
    </div>
    <div>
       <%= f.submit "保存する" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/users/follower.html.erb
<div class="container px-4 px-sm-0">
  <div class="row">
    <%= render 'users/users/list', user:@user %>
    <!--右側のフォロワー一覧表示-->
    <div class="col-md-8">
      <h2><%= @user.name %>のフォロワー</h2>
      <!--ここからtableを使う-->

      <table class="table">
        <% @users.each do |follower| %>
        <tbody>
          <tr>
            <th>
              <%= link_to user_path(follower) do%>
            <%= attachment_image_tag follower, :profile_image, :fill, 100, 100, fallback:"images/no_image.jpg", class: "mt-3 rounded-circle" %>
           <% end %>
            </th>
            <th><%= follower.posts.count %>post</th>
            <th><%= follower.followers.count %>フォロワー</th>
            <th><%= follower.followings.count %>フォロー</th>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/users/following.html.erb
<div class="container px-4 px-sm-0">
  <div class="row">
    <%= render 'users/users/list', user:@user %>
    <!--右側のフォロワー一覧表示-->
    <div class="col-md-8">
      <h2><%= @user.name %>のフォロー</h2>
      <!--ここからtableを使う-->
      
      <table class="table">
        <% @users.each do |followed| %>
        <tbody>
          <tr>
            <th>
              <%= link_to user_path(follower) do%>
            <%= attachment_image_tag follower, :profile_image, :fill, 100, 100, fallback:"images/no_image.jpg", class: "mt-3 rounded-circle" %>
           <% end %>
            </th>
            <th><%= followed.posts.count %>post</th>
            <th><%= followed.followers.count %>フォロワー</th>
            <th><%= followed.followings.count %>フォロー</th>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h1>ユーザー一覧</h1>
    </div>
    <div class="col-4">
      
      <div class="search_form">
      <%= form_with url:search_users_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
  <!--ここから会員一覧表示-->
  <% @users.each do |user| %>
  <div class="row">
    <div class="col-3">
      <%= link_to user_path(user) do%>
        <div class="d-flex justify-content-center">
         <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback:"images/no_image.jpg", class: "mt-3 rounded-circle" %>
        </div>
      <% end %>
    </div>
    <div class="col-7 d-flex flex-row align-items-end">
      <p class="flex-fill">
        <%= link_to user_path(user) do%>
          <%= user.name %>
        <% end %>
      </p>
      <p class="flex-fill"><%= user.posts.count %>posts</p>
      <p class="flex-fill"><%= user.followings.count %>フォロワー</p>
      <p class="flex-fill"><%= user.followers.count %>フォロー</p>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/users/users/like.html.erb
<div class="container px-4 px-sm-0">
  <div class="row">
    <%= render 'users/users/list', user:@user %>
    <div class="col-md-8">
      <h2>いいねした投稿</h2>
      <%= render 'users/posts/list', posts:@like_posts %>
    </div>
  </div>
</div>

app/views/users/users/show.html.erb
<div class="container">
  <% if current_user == @user %>
  <h3>マイページ</h3>
  <% end %>
  <div class="row justify-content-center">
    <p>
    <%= attachment_image_tag @user, :profile_image, :fill, 500, 500, fallback:"images/no_image.jpg",size:'200x200', class:"rounded-circle"; %>
    </p>
  </div>
  <div class="row justify-content-center">
    <h4><%= @user.name %></h4>
  </div>
  <div class="row justify-content-center">
    <p><%= @user.profile %></p>
  </div>
  <!--マイページの時のみプロフィール編集できるようにする-->
    <!--@user.id == current_user ではリンクが作成されなかった。.idはいれてはいけないようだ-->
  <% if current_user == @user %>
  <div class="row justify-content-center">
    <a class="btn btn-outline-secondary col-4 mx-auto" href="/users/<%= current_user.id %>/edit">
      <i class="fas fa-user-cog"></i>
    </a>
  </div>
  <% elsif %>
  <!--フォローボタン作成-->
  <div class="row justify-content-center">
    <% if current_user.following?(@user)%>
      <%= form_with model:@relationship, url:relationship_path, method: :delete, local: true do |f| %>
        <%= f.hidden_field :followed_id, value: @user.id %>
        <%= f.submit "フォロー中", class:"btn btn-success" %>
      <% end %>
    <% else %>
      <%= form_with model:@set_relationship, url:relationships_path, method: :post, local:true do |f|%>
        <%= f.hidden_field :followed_id, value: @user.id %>
        <%= f.submit "フォローする" %>
      <% end %>
    <% end %>
  </div>
  <% end %>
  <!--下半分-->
  <div class="row my-5 d-flex justify-content-center">
    <div class="col-3 d-flex justify-content-center">
      <p><h5><%= link_to "すべての投稿",index_user_post_path(@user.id), class:"text-dark" %></h5></p>
      <span><%= @user.posts.count %></span>
    </div>
    <div class="col-3 d-flex justify-content-center">
      <h5><%= link_to "いいねした投稿", like_user_path(@user.id), class:"text-dark" %></h5>
      <%= @user.likes.count %>
    </div>
  </div>
  
  <div class="row mb-5 d-flex justify-content-center">
    <div class="col-3 d-flex justify-content-center">
      <p><h5><%= link_to "following", following_user_path(@user.id), class:"text-dark" %></h5></p>
      <span><%= @user.followings.count %></span>
    </div>
    <div class="col-3 d-flex justify-content-center">
      <h5><%= link_to "follower", follower_user_path(@user.id), class:"text-dark" %></h5>
      <%= @user.followers.count %>
    </div>
  </div>
  <% if current_user == @user %>
  <div class="row justify-content-center">
    <%= link_to "退会する", confirm_user_path(current_user), class:"text-secondary" %>
  </div>
  <% end %>
</div>