config/routes.rb
Rails.application.routes.draw do

# userと同様にskip: :[password, :registratin]を記述していたのだがするとNo method error Admin#sessionというエラーがでてしまい調べたところ
# skip の記述を消せば解決するとあったのでその通りにするとエラー解決

  devise_for :admin, controllers: {
    sessions: "admins/sessions"
  }
  devise_for :user, skip: [:password], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
   post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# ファイル構成は指定し、urlは変えたくないのでmoduleを使用
 scope module: :users do
  # 通常の指定方法
  # メソッド(get) "url", to: "controller#action", as: "パス名指定"
   get "/", to: "homes#top", as: "root"
   get "/about", to: "homes#about"
   # post "/guest_sign_in", to: "homes#guest_sign_in"
  # resourcesメソッド [index,create,new,show,update,edit,destroy]を自動で作成
  # onlyを使うことで不要なルーティングを制限
   resources :users, only:[:show, :edit, :update, :index, :destroy] do
    # member　で自分でアクションを作ることが出来る。　collectionとの違いはurlにidを指定するかしないか
     member do
       get :confirm
       get :like
       get :following
       get :follower

     end
     collection do
      get :search
     end
    # usersにネストさせることでuser_id/postsというように特定のuserのindexとshowにすることができる
     # resources :posts, only: [:index, :show]
   end
   resources :posts, only:[:new, :create, :destroy, :show, :index] do
    member do
     get :confirm
     get :index_user
     get :show_image
    end
    collection do
     get :search
    end
    resources :comments, only:[:index, :create, :destroy]
    # resource,resourcesのどちらでも実装できた。
    # favoritesのshowページが不要で、idの受け渡しも必要ないので、resourceとなっています。
    # とdmmには書いてあった。
    resource :likes, only:[:create, :destroy]
   end
   resources :relationships, only:[:create, :destroy]
 end

 namespace :admins do
  get "/", to: "homes#top"

  resources :users, only: %i[index show edit update] do
   member do
    get :following
    get :follower
   end

   collection do
    get :search
   end
  end
  resources :posts, only: %i[index show destroy] do
   collection do
    get :search
   end
  end
 end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # refileが指定のカラムにアクセスするためにattachmentメソッドを追加
  attachment :post_image
  # liked_byメソッドを使って引数で渡されたuserのidがlikesテーブルに存在しているかどうかを調べる
  # 存在していたらtrue,していなかったらfalseが返される
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
  
  def commented_by?(user)
    comments.where(user_id: user.id).exists?
  end

  def self.search(keyword)
    where(["title like? or body like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all.page(params[:page]).per(3)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def destroy
  end
  
  def search
    @posts = Post.search(params[:keyword])
    @keyword  = params[:keyword]
    render "index"
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    # dataを新規登録するためのインスタンス作成
    post = Post.new(post_params)
    #投稿のuser_idはログイン中のユーザーidに指定
    post.user_id = current_user.id
    # dataをdataベースに保存するためのsaveメソッドを実行
    post.save
    flash[:notice] = "投稿に成功しました!!"
    redirect_to index_user_post_path(post.user_id)
  end

  def index
    # ページネーションを使う
    @posts = Post.all.page(params[:page]).per(3)
  end

# 最初はindexアクションを定義していたがユーザーごとの投稿一覧ページを実装する必要があったので新しいアクションindex_userを追加して
# urlにuser_idを含むposts/user_id/index_userというルーティングを作った。
  def index_user
    @user = User.find(params[:id])
     # 特定のユーザーの投稿一覧だけを取得したいのでwhereメソッドを使う
    # モデル.where(条件)
    @posts = Post.where(user_id:params[:id]).order(created_at: :desc).page(params[:page]).per(2)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  # 画像の詳細（拡大）表示
  def show_image
    @post = Post.find(params[:id])
  end

  def confirm
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to index_user_post_path(@post.user)
  end



  # def search
  #   @posts = Post.search(params[:keyword]).page(params[:page]).per(5)
  #   @keyword = params[:keyword]
  #   render "index"

  # end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image, :genre)
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/admins/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h1>投稿一覧</h1>
    </div>
    <div class="col-4">
      <div class="search_form">
      <%= form_with url:search_admins_posts_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
  <!--ここから一覧表示-->
  <% @posts.each do |post| %>
    <%= link_to admins_post_path(post) do%>
    <div class="card w-50 mx-auto mt-4 mb-1 shadow-lg">
        <%= attachment_image_tag post, :post_image, class: "card-img-top"%>
      <div class="card-body">
        <div class="row">
          <div class="col-3">
            <%= link_to admins_user_path(post.user) do %>
              <p><%= attachment_image_tag post.user, :profile_image, :fill, 60, 60, fallback:"images/no_image.jpg" , class: "mt-3 rounded-circle"; %></p>
              <span><i class="fa fa-user"></i><%= post.user.name %></span>
            <% end %>
          </div>
          <div class="col-9">
            <p class="card-title">title:<%= post.title %></p>
            <!--コメントマーク-->
            <span><i class="far fa-comment"></i><%= post.comments.count %> | </span>
            <!--いいねボタン-->
            <span>♡<%= post.likes.count %></span>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
    <div class="row justify-content-center">
      <%= paginate @posts %>
    </div>
  </div

app/views/admins/posts/show.html.erb
<div class= "container" >
  <div class= "row">
    <div class= "col">
    
    </div>
  </div>
  <div class="row">
    <div class="col-3 mt-3 d-flex flex-column ">
      <!--プロフィール画像-->
      <%= link_to admins_user_path(@post.user) do %>
      <div class="d-flex justify-content-center">
        <%= attachment_image_tag @post.user, :profile_image, :fill, 150, 150, fallback:"images/no_image.jpg" %>
      </div>
      <!--ユーザーネーム-->
      <div class="d-flex justify-content-center">
        <h4><%= @post.user.name %></h4>
      </div>
      <% end %>
      <!--follow,follower表示-->
      <div class="d-flex">
        <span class="flex-fill"><p class="d-flex justify-content-center">フォロー<%= @post.user.followings.count %></p></span>
        <span class="flex-fill"><p class="d-flex justify-content-center">フォロワー<%= @post.user.followers.count %></p</span>
      </div>
    </div>
    <div class="col-md-8">
      <h2>投稿詳細</h2>
      <!--カード開始-->
      <div class="card w-80 mx-auto mt-4 mb-1 shadow-lg">
        <!--ヘッダー部分-->
        <div class="card header d-flex flex-row">
          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback:"images/no_image.jpg" , class: "mt-3 rounded-circle"; %>
          <div class="flex-grow-1"><%= @post.user.name %></div>
        </div>
        
        <!--画像表示部分-->
        <%= attachment_image_tag @post, :post_image, class: "card-img-top"%>
        <!--ボディ部分-->
        <div class="card-body pt-0 px-0">
          <div class="d-flex">
            <span><i class="far fa-comment"></i><%= @post.comments.count %> | </span>
          
         
            <span>♡<%= @post.likes.count %></span>
        
          <span class="ml-auto"><%= l @post.created_at%></span>
          </div>
          <h5 class="card-title"><%= @post.title %></h5>
          <p class="card-text"><%= @post.body %></p>
          <!--この投稿にされたコメント一覧へのリンク-->
          <%= link_to "この投稿へのコメントを見る", post_comments_path(@post) %>
        </div>
      </div>
    </div>
  </div>
</div>