config/routes.rb
Rails.application.routes.draw do

# userと同様にskip: :[password, :registratin]を記述していたのだがするとNo method error Admin#sessionというエラーがでてしまい調べたところ
# skip の記述を消せば解決するとあったのでその通りにするとエラー解決

  devise_for :admin, controllers: {
    sessions: "admins/sessions"
  }
  devise_for :user, skip: [:password], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
   post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# ファイル構成は指定し、urlは変えたくないのでmoduleを使用
 scope module: :users do
  # 通常の指定方法
  # メソッド(get) "url", to: "controller#action", as: "パス名指定"
   get "/", to: "homes#top", as: "root"
   get "/about", to: "homes#about"
   # post "/guest_sign_in", to: "homes#guest_sign_in"
  # resourcesメソッド [index,create,new,show,update,edit,destroy]を自動で作成
  # onlyを使うことで不要なルーティングを制限
   resources :users, only:[:show, :edit, :update, :index, :destroy] do
    # member　で自分でアクションを作ることが出来る。　collectionとの違いはurlにidを指定するかしないか
     member do
       get :confirm
       get :like
       get :following
       get :follower

     end
     collection do
      get :search
     end
    # usersにネストさせることでuser_id/postsというように特定のuserのindexとshowにすることができる
     # resources :posts, only: [:index, :show]
   end
   resources :posts, only:[:new, :create, :destroy, :show, :index] do
    member do
     get :confirm
     get :index_user
     get :show_image
    end
    collection do
     get :search
    end
    resources :comments, only:[:index, :create, :destroy]
    # resource,resourcesのどちらでも実装できた。
    # favoritesのshowページが不要で、idの受け渡しも必要ないので、resourceとなっています。
    # とdmmには書いてあった。
    resource :likes, only:[:create, :destroy]
   end
   resources :relationships, only:[:create, :destroy]
 end

 namespace :admins do
  get "/", to: "homes#top"

  resources :users, only: %i[index show edit update] do
   member do
    get :following
    get :follower
   end

   collection do
    get :search
   end
  end
  resources :posts, only: %i[index show destroy] do
   collection do
    get :search
   end
  end
 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <%= notice %>
      <%= alert %>
      <nav class="nav navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
           <a class="navbar-brand mb-0" href="/about"><h2>En_Life</h2></a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
               <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link"%>
               </li>
               <li class="nav=item">
                <%= link_to "投稿一覧", posts_path, class: "nav-link"%>
               </li>
               <li>
                 <%= link_to "会員一覧", users_path, class: "nav-link" %>
               </li>
               <li>
                 <%= link_to "新規投稿", new_post_path, class: "nav-link"%>
               </li>
               <li>
                 <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
               </li>
               <li>
                 <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
              </li>
             <% elsif admin_signed_in? %>
               <li>
                <%= link_to "会員一覧", admins_users_path, class: "nav-link" %>
               </li>
               <li>
                <%= link_to "投稿一覧", admins_posts_path, class: "nav-link" %>
               </li>
               <li>
                 <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
               </li>
             <% else %>
               <li>
                <%= link_to "トップページ", about_path, class: "nav-link" %> 
               </li>
               <li>
                <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
               </li>
               <li>
                  <%= link_to "会員一覧", users_path, class: "nav-link" %>
               </li>
               <li>
                 <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
               </li>
               <li>
                 <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
               </li>
             <% end %>
             </ul>
           </div>
        </div>
      </nav>
    </header>
    <main class="mt-5">
      <%= yield %>
    </main>
  </body>
</html>